llm:
  gemini:
    model: gemini-2.5-flash
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  gpt-4.1:
    model: gpt-4.1
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  deepseek-v3:
    model: USD-guiji/deepseek-v3
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  deepseek-r1:
    model: USD-guiji/deepseek-r1
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  claude-thinking:
    model: claude-opus-4-20250514-thinking
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  claude:
    model: claude-3-7-sonnet-20250219
    base_url: ${BASE_URL}
    api_key: ${API_KEY}
